---
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#     .csharpierrc.yml - Configuration file for CSharpier
#     Docs:
#     https://csharpier.com/docs/Configuration
#  ╰──────────────────────────────────────────────────────────────────────────────╯

printWidth: 120
useTabs: false
indentSize: 4
endOfLine: lf
