---
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#     Configuration file for CSpell
#     Docs:
#     https://cspell.org/docs/Configuration
#  ╰──────────────────────────────────────────────────────────────────────────────╯

# ── Versioning ────────────────────────────────────────────────────────────────

$schema: "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json"
version: "0.2"

# ── Config properties ─────────────────────────────────────────────────────────

language: en
allowCompoundWords: true
maxNumberOfProblems: 100
noConfigSearch: true
useGitignore: true
ignoreRandomStrings: true
validateDirectives: true
cache:
  useCache: true
  cacheStrategy: content

# ── Dictionaries ──────────────────────────────────────────────────────────────

dictionaryDefinitions:
  - name: extra
    path: "dictionaries/extra.txt"
    addWords: true
dictionaries:
  - en_US
  - en-gb
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - go
  - python
  - powershell
  - html
  - css
  - cpp
  - csharp
  - bash
  - fonts
  - filetypes
  - npm
  - extra

# ── Includes/Excludes ─────────────────────────────────────────────────────────

ignorePaths:
  - "**/*.editorconfig"
  - "**/.*ignore"
  - "**/.gitattributes"
  - "**/.gitmodules"
  - "**/.cspell.config.yml"
  # Generated file that gets passed to CSpell during runs for some reason.
  - "**/*-megalinter_file_names_cspell.txt"
  # Check commit messages.
  - "**/.git/!(COMMIT_EDITMSG)"
  - "**/.git/!(COMMIT_EDITMSG)/**"
  # Externally sourced so not ours to fix.
  - "**/valestyles/**"
  # This has a bunch of intentionally misspelled words, different languages, etc.
  - "**/Frostpeak.Testing/Data/**"
