---
# --- markdownlint.yml - Configuration file for markdownlint ---
# --- Docs: https://github.com/DavidAnson/markdownlint ---

# Enable all by default.
default: true

extends: null

# MD003/heading-style: Heading style
MD003:
  style: "atx"

# MD004/ul-style: Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent: Unordered list indentation
MD007:
  indent: 4

# MD013/line-length: Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false

# MD024/no-duplicate-heading: Multiple headings with the same content.
MD024:
  siblings_only: true

# MD035/hr-style: Horizontal rule style
MD035:
  style: "---"

# MD040/fenced-code-language: Fenced code blocks should have a language specified.
MD040:
  allowed_languages: []
  language_only: false

# MD044/proper-names: Proper names should have the correct capitalization.
MD044:
  names: []
  code_blocks: false

# MD046/code-block-style: Code block style
MD046:
  style: "fenced"

# MD048/code-fence-style: Code fence style
MD048:
  style: "backtick"

# MD055/table-pipe-style: Table pipe style
MD055:
  style: "leading_and_trailing"
