---
# --- .secretlintrc.yml - Configuration for Secretlint ---
# --- Docs: https://github.com/secretlint/secretlint/blob/master/docs/configuration.md ---

# Use default rules as a base config.
rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
