---
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#     Configuration for stylelint
#     Docs:
#     https://stylelint.io/user-guide/configure/
#  ╰──────────────────────────────────────────────────────────────────────────────╯

extends: stylelint-config-standard
