---
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#     .yamllint - Configuration file for yamllint
#     Docs:
#     https://yamllint.readthedocs.io/en/stable/configuration.html
#  ╰──────────────────────────────────────────────────────────────────────────────╯

extends: default

rules:
  # No consecutive blank lines.
  # Use comment headers for better readability if you need to separate logical sections.
  # Ex: # --- Start of Section ---
  empty-lines:
    max: 1

  # Ensure floats always start with a number.
  # Ex: 0.5 instead of .5.
  float-values:
    require-numeral-before-decimal: true

  # URLs can overflow this, but mappings cannot.
  line-length: false

ignore: |
  **/valestyles/**
